name: Run Mocha Tests

on:
  push:
    branches:
      - main # pushイベントをトリガーとするブランチを指定
      - feature-*
      - master

jobs:
  build:
    runs-on: ubuntu-latest # 実行環境をUbuntuに設定

    steps:
      - name: Checkout repository # リポジトリをチェックアウト
        uses: actions/checkout@v2

      - name: Install Node.js and npm # Node.jsおよびnpmをインストール
        uses: actions/setup-node@v2
        with:
          node-version: 14 # 使用するNode.jsのバージョンを指定

      - name: Install Mocha and ts-node # Mochaおよびts-nodeをインストール
        run: npm install mocha ts-node

      - name: Install TypeScript # TypeScriptをインストール
        run: npm install typescript

      - name: Run Mocha Tests # Mochaテストを実行
        run: npx mocha --require ts-node/register --watch-extensions ts "codewars/test.ts"
